steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - -c
      - |
        ls
        cd /workspace
        mkdir code
        mkdir policy
        git -C /workspace/code clone https://github.com/vishal-kapse/action.git
        git -C /workspace/policy clone https://github.com/GoogleCloudPlatform/policy-library.git

  - name: 'gcr.io/cloud-builders/gcloud-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud -q components update
        gcloud -q components install \
            alpha beta \
            terraform-tools
        gcloud beta terraform vet /workspace/code/action/terraform/tf.json --policy-library=/workspace/policy/policy-library