apiVersion: constraints.gatekeeper.sh/v1alpha1 # Copyright 2019 Google LLC
kind: GCPStorageBucketPolicyOnlyConstraintV1
metadata:
  name: require_bucket_policy_only
  annotations:
    # This constraint is not certified by CIS.
    bundles.validator.forsetisecurity.org/cis-v1.1: 5.02
    bundles.validator.forsetisecurity.org/scorecard-v1: security
    bundles.validator.forsetisecurity.org/healthcare-baseline-v1: security
    description: Checks if Cloud Storage buckets have Bucket Only Policy turned on.
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - organizations/**
  parameters: {}
