name: 'kics'
on:
  push:
    branches:
      - branch
jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - run: ls
      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v1.0
        with:
          # path to file or directory to scan
          path: 'terraform'
          # file path to store result in json format
          output_path: results-dir # optional
          # file path to store source internal representation in JSON format
          payload_path: payload # optional
          # path to directory with queries (default "./assets/queries")
          # queries: # optional
          # verbose scan
          # erbose: # optional
      - name: Show results
        run: |
          cat results-dir/results.sarif
          cat results-dir/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results-dir/results.sarif